// Mock data for complaints
export const mockComplaints = [
  {
    id: "c1a2b3d4e5",
    title: "Water supply interruption in Central District",
    description:
      "We have been experiencing water supply interruptions for the past 3 days. The entire block is affected.",
    status: "resolved",
    department: "Water & Sewage",
    serviceId: "s1",
    submittedBy: "John Citizen",
    location: "Central District, Block A",
    createdAt: "2023-05-15T10:30:00Z",
    updatedAt: "2023-05-18T14:45:00Z",
    attachments: ["image1.jpg", "image2.jpg"],
  },
  {
    id: "f6g7h8i9j0",
    title: "Pothole on Main Street causing traffic hazards",
    description:
      "There is a large pothole on Main Street near the intersection with Oak Avenue. It's causing traffic hazards and has damaged several vehicles.",
    status: "in-progress",
    department: "Roads & Infrastructure",
    serviceId: "s3",
    submittedBy: "Sarah Johnson",
    location: "Main Street & Oak Avenue",
    createdAt: "2023-05-20T09:15:00Z",
    updatedAt: "2023-05-21T11:30:00Z",
    attachments: ["image3.jpg"],
  },
  {
    id: "k1l2m3n4o5",
    title: "Garbage not collected for two weeks",
    description:
      "The garbage collection service has not been operating in our area for the past two weeks. Waste is piling up and causing health concerns.",
    status: "pending",
    department: "Waste Management",
    serviceId: "s5",
    submittedBy: "Michael Brown",
    location: "Western Zone, Residential Area B",
    createdAt: "2023-05-22T15:45:00Z",
    updatedAt: "2023-05-22T15:45:00Z",
    attachments: [],
  },
  {
    id: "p6q7r8s9t0",
    title: "Street lights not working on Park Avenue",
    description:
      "All the street lights on Park Avenue between 5th and 8th Street are not working. This is creating safety issues at night.",
    status: "in-progress",
    department: "Roads & Infrastructure",
    serviceId: "s4",
    submittedBy: "Emily Wilson",
    location: "Park Avenue, 5th-8th Street",
    createdAt: "2023-05-18T18:20:00Z",
    updatedAt: "2023-05-19T10:10:00Z",
    attachments: [],
  },
  {
    id: "u1v2w3x4y5",
    title: "Sewage overflow in Eastern District",
    description:
      "There is a sewage overflow on Elm Street that is causing bad odors and health hazards. It seems to be coming from a broken main line.",
    status: "resolved",
    department: "Water & Sewage",
    serviceId: "s2",
    submittedBy: "Robert Davis",
    location: "Eastern District, Elm Street",
    createdAt: "2023-05-10T08:30:00Z",
    updatedAt: "2023-05-12T16:45:00Z",
    attachments: ["image4.jpg", "image5.jpg"],
  },
  {
    id: "z6a7b8c9d0",
    title: "Noise complaint about construction site",
    description:
      "A construction site on Cedar Road is operating outside of permitted hours, causing excessive noise early in the morning and late at night.",
    status: "pending",
    department: "Public Safety",
    serviceId: "s8",
    submittedBy: "Jennifer Martinez",
    location: "Cedar Road, Northern Area",
    createdAt: "2023-05-23T07:15:00Z",
    updatedAt: "2023-05-23T07:15:00Z",
    attachments: [],
  },
  {
    id: "e1f2g3h4i5",
    title: "Broken playground equipment at Central Park",
    description:
      "The swing set and slide at Central Park playground are broken and pose a safety risk to children. They need immediate repair or replacement.",
    status: "in-progress",
    department: "Public Safety",
    serviceId: "s9",
    submittedBy: "David Thompson",
    location: "Central Park, Southern Region",
    createdAt: "2023-05-17T14:20:00Z",
    updatedAt: "2023-05-18T09:30:00Z",
    attachments: ["image6.jpg"],
  },
  {
    id: "j6k7l8m9n0",
    title: "Request for additional waste bins in market area",
    description:
      "The market area in the Central District needs additional waste bins. The current ones are always overflowing, especially on weekends.",
    status: "resolved",
    department: "Waste Management",
    serviceId: "s6",
    submittedBy: "Lisa Anderson",
    location: "Central District, Market Area",
    createdAt: "2023-05-05T11:45:00Z",
    updatedAt: "2023-05-08T13:20:00Z",
    attachments: [],
  },
  {
    id: "o1p2q3r4s5",
    title: "Water quality concerns in Northern Area",
    description:
      "Residents in the Northern Area have noticed discolored water coming from their taps. We are concerned about water quality and safety.",
    status: "in-progress",
    department: "Water & Sewage",
    serviceId: "s1",
    submittedBy: "James Wilson",
    location: "Northern Area, Residential Zone C",
    createdAt: "2023-05-19T16:30:00Z",
    updatedAt: "2023-05-20T10:15:00Z",
    attachments: ["image7.jpg"],
  },
  {
    id: "t6u7v8w9x0",
    title: "Illegal dumping behind shopping center",
    description:
      "There has been ongoing illegal dumping of construction waste behind the shopping center on Maple Drive. This has created an eyesore and potential environmental hazard that needs to be addressed immediately.",
    status: "pending",
    department: "Waste Management",
    serviceId: "s7",
    submittedBy: "Thomas Clark",
    location: "Maple Drive, Western Zone",
    createdAt: "2023-05-21T13:10:00Z",
    updatedAt: "2023-05-21T13:10:00Z",
    attachments: ["image8.jpg", "image9.jpg"],
  },
]

// Mock data for services
export const mockServices = [
  {
    id: "s1",
    name: "Water Supply Management",
    description:
      "Management and maintenance of water supply infrastructure including pipes, pumps, and treatment facilities.",
    department: "Water & Sewage",
    status: "active",
    createdAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "s2",
    name: "Sewage System Maintenance",
    description: "Regular maintenance and emergency repairs of the sewage system throughout the sub-city.",
    department: "Water & Sewage",
    status: "active",
    createdAt: "2023-01-01T00:00:00Z",
  },
  {
    id: "s3",
    name: "Road Maintenance",
    description: "Repair and maintenance of roads, including pothole fixing, resurfacing, and structural repairs.",
    department: "Roads & Infrastructure",
    status: "active",
    createdAt: "2023-01-15T00:00:00Z",
  },
  {
    id: "s4",
    name: "Street Lighting",
    description: "Installation, maintenance, and repair of street lights to ensure public safety and visibility.",
    department: "Roads & Infrastructure",
    status: "active",
    createdAt: "2023-01-15T00:00:00Z",
  },
  {
    id: "s5",
    name: "Household Waste Collection",
    description: "Regular collection of household waste from residential areas according to scheduled routes.",
    department: "Waste Management",
    status: "active",
    createdAt: "2023-02-01T00:00:00Z",
  },
  {
    id: "s6",
    name: "Public Area Cleaning",
    description: "Cleaning and maintenance of public areas, parks, and streets to ensure cleanliness and hygiene.",
    department: "Waste Management",
    status: "active",
    createdAt: "2023-02-01T00:00:00Z",
  },
  {
    id: "s7",
    name: "Waste Disposal Management",
    description: "Management of waste disposal sites and implementation of proper waste disposal practices.",
    department: "Waste Management",
    status: "maintenance",
    createdAt: "2023-02-01T00:00:00Z",
  },
  {
    id: "s8",
    name: "Noise Control",
    description: "Monitoring and enforcement of noise regulations to maintain quality of life in residential areas.",
    department: "Public Safety",
    status: "active",
    createdAt: "2023-03-01T00:00:00Z",
  },
  {
    id: "s9",
    name: "Public Facility Maintenance",
    description: "Maintenance and repair of public facilities such as parks, playgrounds, and community centers.",
    department: "Public Safety",
    status: "active",
    createdAt: "2023-03-01T00:00:00Z",
  },
  {
    id: "s10",
    name: "Housing Assistance",
    description: "Assistance programs for housing-related issues including subsidies and maintenance support.",
    department: "Housing",
    status: "active",
    createdAt: "2023-04-01T00:00:00Z",
  },
]
